INSERT INTO ZOO (nombre,CIUDAD,PAIS,TAMAÑO,PRESUPUESTO_ANUAL) VALUES('Zoologico A','Ciudad A','Pais A',2000,5000);
INSERT INTO ZOO (nombre,CIUDAD,PAIS,TAMAÑO,PRESUPUESTO_ANUAL) VALUES('Zoologico B','Ciudad B','Pais B',2000,5000);
INSERT INTO ZOO (nombre,CIUDAD,PAIS,TAMAÑO,PRESUPUESTO_ANUAL) VALUES('Zoologico C','Ciudad C','Pais C',2000,5000);
INSERT INTO ZOO (nombre,CIUDAD,PAIS,TAMAÑO,PRESUPUESTO_ANUAL) VALUES('Zoologico D','Ciudad D','Pais D',2000,5000);
  	  	  

INSERT INTO ESPECIE (ESPECIE_ANIMAL,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,PELIGROEXTINCION) VALUES('TIGRE','TIGRE COMUN','PANTERA TIGRIS','FELIDAE','S');
INSERT INTO ESPECIE (ESPECIE_ANIMAL,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,PELIGROEXTINCION) VALUES('OSO','OSO PANDA','AILUROPODA MELANOLEUCA','URSIDAE','S');
INSERT INTO ESPECIE (ESPECIE_ANIMAL,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,PELIGROEXTINCION) VALUES('ELEFANTE','ELEFANTE AFRICANO','LOXODONTA AFRICANA','ELEPHANTIDAE','S');
INSERT INTO ESPECIE (ESPECIE_ANIMAL,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,PELIGROEXTINCION) VALUES('GORILA','GORILA ORIENTAL','GORILLA BERINGEI','HOMINIDAE','S');	  	  	  	  

INSERT INTO ANIMAL (ZOOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE) VALUES (1,1,'Macho','2010-10-25','India','Asia');
INSERT INTO ANIMAL (ZOOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE) VALUES (2,3,'Hembra','2015-06-12','Brasil','América del Sur');
INSERT INTO ANIMAL (ZOOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE) VALUES (3,2,'Macho','2018-03-21','China','Asia');
INSERT INTO ANIMAL (ZOOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE) VALUES (4,4,'Hembra','2016-11-07','Kenia','África');
INSERT INTO ANIMAL (ZOOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE) VALUES (3,1,'Macho','2014-09-18','Rusia','Europa');